### PR TITLE
Comfyui-support

### PR DESCRIPTION
**Pull request by RobeSantoro**
Add ComfyUI support to the addon.

This branch was used for the production of my latest [projection mapping show](https://www.blendingpixels.com/projects/medimex-2024), so expect bad code, bad practices, I was a bit in a hurry...

Anyway It's working, now I just need to make it right... :)

### CODE REVIEW

**Comment by benrugg** [comment]
Hey @RobeSantoro - just wanted to let you know I haven't forgotten about this. I truly apologize for not looking at it in detail yet. I will still try to that soon!

**Comment by RobeSantoro** [comment]
> Hey @RobeSantoro - just wanted to let you know I haven't forgotten about this. I truly apologize for not looking at it in detail yet. I will still try to that soon!

Hi @benrugg, take your time! You can easily merge it and try it on this branch. You should keep it on this separate branch for others to test and contribute. The first thing I'm going to do is implement a proper upload for images to the API. This way, it will also be possible to specify a remote address instead of only the localhost, and run comfy on a powerful remote computer. 

By working on a Mac laptop, I discovered how slow the generation could be, especially if you give depth, normal, and openpose as conttrolnet.

**Comment by noise2014** [comment]
i am looking forward for comfyui support

**Comment by RobeSantoro** [comment]
@benrugg Hi Ben! Please merge the comfyui-support branch so I can test it and start working on fixing issues. The first issue that will arise will be the name of the repo, which is used to check if the installation is correct. For comfyui support testing, I renamed the repo "AI-Render-ComfyUI-Support"

Do you want me to fix it beforehand and make a new PR?

**Comment by benrugg** [comment]
Hey, so sorry I haven't taken a look at this inkre detail yet. I will merge this in now and I'll be quick to approve future PR's on this branch. And then as soon as I have more time, I'll test it out and give any feedback. Thanks for making this happen!

**Comment by benrugg** [comment]
And yes, that name check will be important, and also I think there might be a secondary issue to solve: when downloading the repo as a zip file, GitHub automatically nests the code in a top-level folder, so you can't just take that zip and install it as an add-on in Blender.

We could solve this by creating instructions on how to unzip and then rezip the extracted files. If there's a better solution, I'm all ears!

**Comment by RobeSantoro** [comment]
@benrugg Hey Ben, I tested the installation procedure on Windows.

The top-level folder in the zip is ok for the typical "Install from disk" procedure.

I tried to fork the WIKI, but it's a bit convoluted on GitHub...
... so I created the instructions in the README.md of the comfyui-support branch.

Let's move any future conversation to the [https://github.com/benrugg/AI-Render/issues/146](Feature Request: Add ComfyUI as a backend)

Bye

**Comment by benrugg** [comment]
@RobeSantoro Sounds great. I just merged the newest PR, and I'll plan to move any future conversation to that issue.

**Pull request merged**
