### PR TITLE
Remove all analytics

### PR DESCRIPTION
**Pull request by InconsolableCellist**
Removes all analytics, which previously the user wasn't allowed to opt out of.

### CODE REVIEW

**Comment by benrugg** [comment]
This is a good way to handle this. I'm happy to leave this up as a way for anyone to easily download a version that doesn't have analytics. 

Is there a better way than simply leaving this as on open pull request? Should I merge this into a different branch?

**Comment by InconsolableCellist** [comment]
:+1: I'm glad you're open to the idea, and a different branch or another version on the release page would be useful. An even better solution would be to have a checkbox for opting out of analytics in the config page, and you could use the download page of Github to get an indication as to how many people are likely installing it. It's mostly the lack of choice I object to when I get software like this. 

If AI-Render already has a user preferences object, it should be a quick fix to add that feature

**Comment by benrugg** [comment]
Yeah, that's a good point. Maybe I'll just add an easy way to opt out. I think that would be a lot easier than keeping multiple releases up to date, and it would also be more visible to the vast majority of users (who are getting it from Blender Market and Gumroad, rather than Github). 

I'll add this to my todo list.

**Comment by InconsolableCellist** [comment]
:+1: Thanks

**Comment by benrugg** [comment]
Thanks for bringing it up. I added analytics just as a way for me to get a sense of how many people are actively using it, and I've barely checked it. I should have added an opt-out when I added this in the first place.

**Comment by InconsolableCellist** [comment]
I was probably too quick to assume malicious intent or a deliberate choice rather than a one-time decision that wasn't revisited. I was looking for an alternative to Stability's Blender addon, which requires Dream Studio and also has some analytics in it, and came across this.

**Comment by benrugg** [comment]
That's fair. It's really easy to assume that, since so many apps like this are sort of nameless/faceless.

**Comment by benrugg** [comment]
This is now done and released: https://github.com/benrugg/AI-Render/releases/tag/v0.7.5

(or update through AI Render add-on preferences)

**Pull request closed without merging**
