### PR TITLE
[stable horde] Retrieve file from r2

### LINKED ISSUE #66: Switch Stable Horde backend to R2 serving
### Describe the bug

Stable horde switched recently to defaulting to r2: True. I noticed [in the code](https://github.com/benrugg/AI-Render/blob/e81ad4976d339ba585c379ac85152ed914d483e1/sd_backends/stablehorde_api.py#L134) you don't explicitly specify `r2:false` when sending b64 images, so you need to update the code to either specify `r2:false` or better, adjust your code to allow it to download images from a URL, instead of decoding b64 and use default r2 serving. Using R2 is the suggested approach from the stable horde (and returns images with less compression) as it results in less bandwidth passing through our servers.

### To reproduce

Stable Horde backend is probably broken right now.

### Error log

N/A

### Environment

_No response_

### Screenshots/video

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tijszwinkels**
fixes #66, #67

### CODE REVIEW

**Comment by benrugg** [comment]
Looks great - I'll release this right now. Thanks for fixing it @tijszwinkels

**Comment by benrugg** [comment]
btw, you should see if you can get AI Render added to the Plugins section on the stable horde home page!

**Comment by tijszwinkels** [comment]
> btw, you should see if you can get AI Render added to the Plugins section on the stable horde home page!

It's been added. :)

**Comment by benrugg** [comment]
Nice 🙌

**Pull request merged**
