### PR TITLE
Added Inpainting and Outpainting Support

### PR DESCRIPTION
**Pull request by AyaanShah2204**
Hello @benrugg 

This PR should add inpainting and outpainting support to AI Render:
- I have added a frontend for both functionalities keeping with the general UI design
- I have added operators and helper functions keeping with the general design pattern

Please let me know if you have any ideas :)

### CODE REVIEW

**Comment by benrugg** [comment]
Wow, very nice! I will check this out as soon as I can!

**Comment by benrugg** [comment]
I made one change, which is that I'm only showing the inpaint/outpaint panels for backends that support them. I'll release this all now!

**Comment by benrugg** [comment]
Btw, I tested on my PC just now and I would suggest adding a bit more info to the installation wiki page. You might want to say that you need to run the `.exe` file first, and download SD models (manually or through the gui).

**Comment by AyaanShah2204** [comment]
Thanks! I'm working on migrating the docs from the wiki on my fork to the Shark repo, I'll add those changes there.

**Comment by benrugg** [comment]
Sounds good. If you want to update the help link in AI Render after that, I'll push that release quickly

**Pull request merged**
