### PR TITLE
Add ability to change image filename

### LINKED ISSUE #44: Feature Request: Add seed (and possibly other params) to output filename
### Describe the feature you'd like to see:

Please add the ability to save the generation seed in the file name.
So I could repeat the result I like. Right now there is a set of digits which looks like a seed, but it has nothing to do with the actual seed. In the related field other digits are displayed.
Also it would be cool if you could add possibility to animate based on previous generation result. So I could generate e.g. 50 shots automatically. 
Right now the animation can only be rendered based on the original image. Thank you!

### Additional information

_No response_

### LINKED ISSUE #132: Feature Request: Add the ability to override the filename
### Describe the feature you'd like to see:

There is currently an issue asking to add more info to the filename #44 
My request is to actually allow overriding the with custom formatting.

Instead of formatting a predefined string here
https://github.com/benrugg/AI-Render/blob/75acec4a5d4ac18624df6b915328225afbcc24f2/operators.py#L367
using something like
```python
def sd_generate(scene, prompts=None, use_last_sd_image=False, custom_filename="ai-render-{timestamp}-{suffix}"):
.....
  before_output_filename_prefix = cutom_filename.format(timestamp = timestamp, seed = seed, suffix = "-1-before")
....
```

Giving the option to add more info, or in my case where I want the filename to be the same every render. Since I don't want a bunch of images for each render, just whatever the last one was.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LeonardMeagher2**
Adds the ability to change how files are named in advanced options
- If the template string is removed, it uses the default.
- Allows more details to be added to the filename optionally and however the user wants

Closes #132 
Closes #44

### CODE REVIEW

**Comment by LeonardMeagher2** [comment]
Might make a separate template for animated images or just hide this when using animations. 
Haven't tested this yet, just made the code changes. Going to review myself before taking it out of draft.

**Comment by benrugg** [comment]
Sweet - I will try to check this out tonight, if possible. Let me know when it's ready for me to look at.

**Comment by LeonardMeagher2** [comment]
@benrugg It is ready for review, I've tested locally and am happy on my side.
I imagine you already see this, but my commits are terrible so probably squashing them would be best

**Comment by benrugg** [comment]
@LeonardMeagher2 thanks for implementing this! (And the other PR, too). I will review them both as soon as possible - hopefully today.

**Comment by benrugg** [comment]
I just submitted an update to your fork: https://github.com/LeonardMeagher2/AI-Render/pull/2

I have a few more thoughts on what we should do to make it a little more foolproof for others. Would you be ok working on this a bit more?

- [ ] Strip any non-available template keywords before attempting the format in get_image_filename()

- [ ] Replace invalid filename characters in prompt and negative_prompt (currently this just fails silently)

- [ ] Make sure filename isn't too long (ideally, limit the size of prompt and negative_prompt to fill the available space after all other keywords have been used)

- [ ] Should we offer a hyphenated version of prompt/negative_prompt as a keyword option?

- [ ] Should we make {suffix} part of the template that is controllable? (would probably need to add suffix automatically if it wasn't specified??)

**Comment by benrugg** [comment]
Feel free to push back on anything or start a conversation about any of it!

**Comment by LeonardMeagher2** [comment]
I like the ideas, I'll try and see what I can do!

**Comment by benrugg** [comment]
Nice, thank you again for working on it!

**Comment by LeonardMeagher2** [comment]
@benrugg I've added filename sanitization, do you want to try it out again and see if that's enough?
I might be able to remove the suffix stuff all together, since we can replace data blocks for the images.

**Comment by benrugg** [comment]
@LeonardMeagher2 I will check this out as soon as I can. It will probably be tomorrow, unfortunately. For the suffix part, I don't think we can remove it altogether, because then the files would overwrite each other (on the disk, not necessarily in Blender).

**Comment by benrugg** [comment]
About to release this. Thank you again for all this work! I made a couple small changes: sanitizing the template of any vars that aren't allowed, and allowing a bit more punctuation and spaces again. (I figure it would be nice to be able to copy and paste the prompt back from the filename).

**Pull request merged**
