### PR TITLE
Stable horde support

### PR DESCRIPTION
**Pull request by tijszwinkels**
This PR adds support for the Stable Horde crowdsourced distributed GPU cluster to AI Render.

- Wrote the Stable Horde SD back-end
- Stable Horde requires the webp image format for sending and receiving, so made the image format dynamic based on selected back-end
- Changed configuration screen to add backend selection drop-down at the top. Back-end selection now isn't only for Local back-ends, but includes remote backends (Dream Studio, Stable Horde) as well.
- If no api-key given for Stable Horde, use the 'anonymous' (0000000000) one as default
- Added some documentation

### CODE REVIEW

**Comment by tijszwinkels** [comment]
If you prefer, I can squash it into a single commit.

**Comment by benrugg** [comment]
At first glance, this looks awesome. I will run it through its paces as soon as I can. This week I'm back to other projects, so it will probably be a couple days before I can devote time to it. I hope that's ok!

**Comment by benrugg** [comment]
I haven't forgotten about this. I will still try to look at this in detail very soon!

**Comment by stuckinstatespace** [comment]
Appreciate the update, but no sweat! I'm not in a rush! :)

**Comment by benrugg** [comment]
I'm not sure if there is a better way for me to push code to this pull request. See my commit here 72fbdbde886d8d7a4800caf9f01bc78278e9ab68

Everything is looking good, but I wasn't able to successfully test Stable Horde, because it keeps timing out. I even increased the timeout to 120 seconds, but I still haven't been able to get a single image completed yet.

**Comment by benrugg** [comment]
One more commit: b283225f37a5d6a6c6bf9927adba3d5ca5d5da02. Sorry this isn't coming through automatically.

I increased the timeout, and I was able to test it all. It's looking great. I'm going to merge into master, and I will release later this week with some other additional features.

Let me know if you have any other thoughts or changes!

**Comment by tijszwinkels** [comment]
Thanks for merging!

The Stable Horde is currently pretty overloaded. Ironically there seems to be enough GPU capacity, but the back-end was never designed for the load they were exposed to when they made SD 2.0 publicly available for free.

The author has been refactoring the back-end all weekend. Current estimate is that it will be released tomorrow.

**Comment by benrugg** [comment]
Ah, cool, that makes sense. Yeah, the site itself was down for a while this morning, so it must be getting a lot of traffic!

Thank you for your work adding support for Stable Horde!

**Comment by db0** [comment]
Stable horde switched recently to defaulting to `r2: True`. I noticed in the commit you didn't explicitly specify `r2:false` when sending b64 images, so you might want to update the code to either specify `r2:false` or adjust your codeto allow it to download images instead of decoding b64 and use r2 serving which is the suggested approach from the stable horde (and returns images with less compression)

**Comment by benrugg** [comment]
Thanks for letting us know, @db0. @tijszwinkels, would you want to update this? And maybe we can move the conversation to the new issue: https://github.com/benrugg/AI-Render/issues/66

**Pull request merged**
