### PR TITLE
Negative prompting

### PR DESCRIPTION
**Pull request by marianobastiUNRN**
Add negative prompting (sorry for the commit mess, no UI changes)

### CODE REVIEW

**Comment by benrugg** [comment]
This is rad. I don't think DreamStudio supports this yet, so we'll need to make it only appear (and be used) with Automatic1111. Are you up for coding this? 

Here are the methods already in place for checking this:
```
if utils.do_use_local_sd() and utils.local_sd_backend() == "automatic1111":
```

**Comment by marianobastiUNRN** [comment]
On it!

**Comment by marianobastiUNRN** [comment]
Done! I figure in a future when DreamStudio adds negative prompting, and when other backends are added, this will have to change.

**Comment by benrugg** [comment]
This is great. It will require a bit of work to merge with my changes in the animation branch (which I'm about to release tomorrow), so I will tackle the merge once that's done. Thanks for working on this!

**Comment by marianobastiUNRN** [comment]
Awesome, I'll be attentive to that push!

**Pull request closed without merging**
