### PR TITLE
Shark Backend

### PR DESCRIPTION
**Pull request by AyaanShah2204**
PR in response to Issue #96 

- We have added functionality for generating images and upscaling through SHARK. 
- img2img generation works, but we have some internal server issues in upscaler that we are currently fixing
- How do you suggest we integrate our inpainting and outpaininting API?

### CODE REVIEW

**Comment by AyaanShah2204** [comment]
I have left some of the Automatic1111 help urls because the shark backend is closely based off of the Automatic1111 backend.

**Comment by benrugg** [comment]
Nice, I should be able to check this out tomorrow. How can I test the shark backend? Is there an install readme?

Re: inpainting and outpainting, I don't really know. I haven't supported that on any of the other backends.

**Comment by AyaanShah2204** [comment]
Sure! You should be able to test that out as soon as a minor PR on the Shark repo gets merged. I'll attach an install readme and let you know as soon as that's done.

For the inpainting and outpainting:
Let me know if you have any ideas about how it should be from a UI perspective. I'll start implementing the backend once this PR lands.

**Comment by benrugg** [comment]
Just checked this out. It looks like `shark_api.py` needs to implement a few more of the public support functions (like `get_samplers()`, etc). See all the functions starting on line 221 of `stability_api.py`. 

And then let me know when I can test SHARK out.

**Comment by benrugg** [comment]
Nice! Any update on a readme for SHARK installation?

**Comment by AyaanShah2204** [comment]
I’m doing some testing with the latest release of SHARK to ensure that it works. I’ll attach a Readme to the Wiki hopefully by EOD!

**Comment by benrugg** [comment]
Sounds great

**Comment by AyaanShah2204** [comment]
The integration seems to work on my end. Please run with auto-upscaling turned off because we're still trying to fix the internal server error there. 

I have added the SHARK installation instructions in the Wiki on my fork: https://github.com/AyaanShah2204/AI-Render/wiki/Shark

Please let me know if you run into any issues :)

**Comment by benrugg** [comment]
I went to test this just now and I had mistakenly mis-remembered it as being Mac-only, not PC-only. I don't have a good test PC available right now, so I'll take your word for it that it all works. 

Looking at it again, I think the one additional thing that needs to happen is changing the instruction and help links to reflect SHARK. (With over 50k users, I get more customer support requests than I would like, and many can be avoided by good help links). 

The three main places that would be the most helpful:
 - Instruction text in preferences panel when switching to SHARK
 - A wiki help article for installation (already done, just needs to be used)
 - A wiki help article for troubleshooting errors

Does that sound ok?

**Comment by AyaanShah2204** [comment]
Hello Ben,
- I have updated the error handling to point to Shark specific wiki links.
- The wiki links currently point to the Wiki on my fork. Feel free to copy them over to yours.
- I have not added any specific error handling for the upscaler except a note in the troubleshooting docs because we expect the issue to be resolved sometime this week.

Please let me know if that sounds good and I will commence work on the inpainting / outpainting PR

**Comment by benrugg** [comment]
Looks great. I'll push out a release in a moment!

**Comment by benrugg** [comment]
The new release is now live on github, and in BlenderMarket and Gumroad!

https://github.com/benrugg/AI-Render/releases/tag/v0.8.0

**Pull request merged**
