### PR TITLE
Negative prompting

### PR DESCRIPTION
**Pull request by marianobastiUNRN**
For v0.5.3
Gotta discuss out how to implement it for the animated prompt. I propose using the same format Deforum uses, with weighted prompting:
`1:A sky at dawn:1, mountains:0.7, Ugly:-1, bad quality:-2`

### CODE REVIEW

**Comment by benrugg** [comment]
Yeah, this is a great idea. Implementing prompt weight itself would be a nice addition. Do you know if that's possible with Automatic1111's API?

**Comment by marianobastiUNRN** [comment]
A1111 didn't like the idea lol [https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/70#issuecomment-1236563562](url) so it's a hard no.
So another solution is needed for the animated prompts. Maybe separating with a substring like `1:A sky at dawn, mountains|neg:Ugly, bad quality` or something more elegant.

**Comment by benrugg** [comment]
Yeah, I think we could do that route, or the other option would be allowing a separate block, like this: 

1: A mountain at sunset
10: whatever

Negative:
1: ugly
5: bad drawing

This decoupling would have a couple advantages. You could have a single negative prompt and not have to repeat it. Or you could do different combinations, since the start frames don't have to match up. 

But I'm not sure if it would be as clear. What do you think?

**Comment by marianobastiUNRN** [comment]
I agree is not that clear, but those benefits are good to have. How about two separate `layout.row()` ?
Might I ask how prompt interpolation is made between frames?

**Comment by benrugg** [comment]
There's no interpolation between frames - it just uses one prompt until it gets to the next one. Is that what you were asking?

**Comment by benrugg** [comment]
Btw, if you want to keep working this, that's wonderful. If you'd rather leave it here, I can pick it up soon. 

I will be back to working on other projects (not AI Render) for the next couple weeks, but since this is so close, it would be cool to release it sooner!

**Comment by marianobastiUNRN** [comment]
> interpolation between frames

Yes thatt hing. I found these scripts meant for animation too [https://github.com/amotile/stable-diffusion-backend/tree/master/src/process/implementations/automatic1111_scripts](url).
I won't be pursuing more development for the animated prompts.
 It'd be nice to incorporate this for the time being

**Comment by marianobastiUNRN** [comment]
Finally made it work with animation, leaving space for animated prompts.

**Comment by benrugg** [comment]
This is great. I will add in the animated prompts as soon as I can. (I won't be focusing on AI Render for the next couple weeks, but if I can squeeze in some time, I will!)

**Comment by benrugg** [comment]
I've just added support for animated negative prompts, and I'm merging this in now. I'll be releasing with some other updates later this week. Thank you for your work on this!

**Comment by benrugg** [comment]
For some reason, the way I checked out and then pushed more code to this pull request, it created a new pull request. So I will close this one. But your code is merged into master now.

**Pull request closed without merging**
